### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cngeru** [jsaari97/react-realtime-drawing#3]
1. Connect to websockets
2. Custom Shapes (Rectangles and ellipses)
3. Add text
4. Add images

**Comment by jsaari97** [comment]
Hello, thanks for checking out this library!

> 1. Connect to websockets

This is already possible by hooking up your websocket logic with the `onChange` functions.
For example, provide the `useRealtimeDrawer` hook an `onChange` function that sends a websocket message to the server with the function payload when the user draws on the canvas. For the viewer you'll be listening for websocket messages from the server and when received you pass them to the `useRealtimeViewer`'s `onChange` function to render the results.

> 2. Custom Shapes (Rectangles and ellipses)
> 3. Add text
> 4. Add images

These features are unfortunately out-of-scope for this project. This library is meant for freehand drawing only.

For this purpose I recommend checking out [react-konva](https://github.com/konvajs/react-konva). It's a much more comprehensive library with support for shapes, text, images and more!
