### ISSUE TITLE
Can't figure out how to reset the drawing without reloading page. 

### ISSUE THREAD

**Issue by white731** [jsaari97/react-realtime-drawing#4]
Hi there, I admit I'm a bit new to coding so I'm sorry if this is already there but I'm just missing it. I can't figure out how to clear the canvas. Any thoughts? 

Thanks for the cool library!

**Comment by jsaari97** [comment]
Hello, thanks for checking out this library!

Both `useRealtimeDrawer` and `useRealtimeViewer` hooks return a `reset` function that clears the canvas. You can check out this [example](https://github.com/jsaari97/react-realtime-drawing/blob/master/example/src/main.js).

I understand that it can be tricky to find as I haven't gotten around documenting the API yet 😅 

Good luck on your coding journey! :)
