### ISSUE TITLE
Multiple real-time boards

### ISSUE THREAD

**Issue by Temidayomichael** [jsaari97/react-realtime-drawing#9]
Hello, is it possible to have multiple drawers and viewer boards on same app? For example an E-Learning platform with multiple rooms/classes, can I have boards for each class? 
Also how do I draw shapes? 

Kind regards.

**Comment by jsaari97** [comment]
Multiple instances are possible.

This library only supports freehand drawing, so if you need support for shapes, have a look at [react-konva](https://github.com/konvajs/react-konva), which has a lot more features.
